server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh           #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**    #断言，路径相匹配的进行路由
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:  #各断言之间通过且关联
            - Path=/payment/lb/**
#            - Before=2017-01-20T17:42:47.789-07:00[America/Denver]
#            - After=2020-06-14T12:17:52.306+08:00[Asia/Shanghai]
#            - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]
#            - Cookie=chocolate, ch.p #This route matches the request has a cookie named chocolate who’s value matches the ch.p regular expression.  #curl命令测试
#            - Header=X-Request-Id, \d+ #This route matches if the request has a header named X-Request-Id whose value matches the \d+ regular expression (has a value of one or more digits). #curl命令测试
#            - Host=**.somehost.org,**.anotherhost.org
#            - Method=GET
#            - Query=baz #This route would match if the request contained a baz query parameter.
#            - RemoteAddr=192.168.1.1/24

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka